# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/cache/**"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_BASE_URL,NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect /confirm to the API route
[[redirects]]
  from = "/confirm"
  to = "/api/confirm"
  status = 302
  force = true

# Redirect old API route to new API route
[[redirects]]
  from = "/api/newsletter/confirm"
  to = "/api/confirm"
  status = 302
  force = true